title: "Quarto Template"
author: "Data Science and Machine Learning"
project:
  type: website
  output-dir: website
  preview:
    port: 2222
  render:
    - index.qmd
format:
  html:
    pagel-layout: article
    theme: cosmo